name: gemini_review

on:
  pull_request:
    types: synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Create comments
      run: |
        cat << EOF > comments
        もう一度レビューするには以下のコマンドを実行してね
        /gemini review
        EOF

    - name: Post comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.html_url }}
      run:
        gh pr comment -F ./comments "${URL}"